language: go
go:
  - tip

install:
  - go get github.com/davecgh/go-spew/spew
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/pkg/math
  - go get gopkg.in/alecthomas/kingpin.v2

script:
  - $GOPATH/bin/ginkgo -r --randomizeAllSpecs --randomizeSuites --race --trace
